import type { Resource } from "../types.js";

export const resources: Resource[] = [
  {
    uri: "medicine-wheel://directions/all",
    name: "Medicine Wheel - Four Directions",
    description: "Complete teachings for all four sacred directions from Ojibwe/Anishinaabe tradition",
    mimeType: "application/json",
    content: {
      east: {
        ojibwe: "Waabinong",
        color: "Yellow",
        season: "Spring",
        life_stage: "Birth to 7 years",
        stage_name: "Good Life",
        medicine: ["Tobacco"],
        element: "Spirit entering physical world",
        teachings: [
          "New beginnings and vision",
          "Creator gifts: choice of parents, spiritual journey, growth",
          "Daily thanksgiving and gratitude for all relations",
          "First day-fast at age 7",
        ],
        practices: [
          "Place tobacco outside daily",
          "Acknowledge all relations",
          "Opening ceremonies",
          "Vision inquiry",
        ],
        research_application: "Vision inquiry, new ideas, opening ceremonies, honor knowledge's aliveness",
      },
      south: {
        ojibwe: "Zhaawanong",
        color: "Red",
        season: "Summer",
        life_stage: "7 to 14 years",
        stage_name: "Fast Life / Wandering into Youth",
        medicine: ["Cedar (Grandmother)"],
        element: "Life awake and dancing",
        teachings: [
          "Growth and embodiment",
          "Spirit nurturance critical",
          "Elders invite, don't command",
          "Mentorship heals",
          "Intuition never deceives",
        ],
        practices: [
          "Sweat lodges",
          "Dancing and celebration",
          "Berry harvesting",
          "Listen to spirit's warnings",
        ],
        research_application: "Physical embodiment, land engagement, growth practices, youth participation, hands-on learning",
      },
      west: {
        ojibwe: "Epangishmok",
        color: "Black",
        season: "Fall",
        life_stage: "35 to 49 years",
        stage_name: "Truth & Planning",
        medicine: ["Sage", "Strawberry"],
        element: "Ripening harvest, adult responsibility, transformation",
        teachings: [
          "Death not ending but continuous transformation",
          "Accept change and loss",
          "Heart (not head) leads to peace",
          "Forgiveness through strawberry teaching",
        ],
        practices: [
          "Talking circles",
          "Dream work",
          "Storytelling",
          "Smudging with sage",
          "Forgiveness ceremonies",
        ],
        research_application: "Reflection, emotional processing, relational healing, unpacking trauma, forgiveness frameworks",
        strawberry_teaching: "Brother kills brother; mourns years; strawberry grows on grave; eating berry = freedom (release of blame)",
      },
      north: {
        ojibwe: "Kiiwedinong",
        color: "White",
        season: "Winter",
        life_stage: "49+ years",
        stage_name: "Doing & Elder",
        medicine: ["Cedar", "Stories"],
        element: "Rest, reflection, wisdom, remembrance",
        teachings: [
          "Elders teach via ceremony and story",
          "Feed ancestors (maintain relational continuity)",
          "Wisdom = integration of all stages",
          "Winter storytelling circles",
        ],
        practices: [
          "Spirit feeding ceremonies",
          "Winter storytelling",
          "Fasting for direction every 7 years",
          "Elder councils",
          "Feast gatherings",
        ],
        research_application: "Wisdom synthesis, ancestral consultation, long-term reflection, community teaching, closing ceremonies",
        spirit_feeding: "Bakademe – zhamzhenung (We are hungry; feed us) - call to feed ancestors",
      },
      seven_stages: [
        { stage: 1, name: "Good Life", ages: "0-7", focus: "Unconditional love, identity grounding, first fast" },
        { stage: 2, name: "Fast Life", ages: "7-14", focus: "Vision quest prep, gendered mentorship, circle induction" },
        { stage: 3, name: "Wandering", ages: "14-21", focus: "Find teachers, explore ('I wonder...'), discover self" },
        { stage: 4, name: "Truth", ages: "21-28", focus: "Mirror self, name gifts, speak truth" },
        { stage: 5, name: "Planning", ages: "28-35", focus: "Integrate learning into action strategy" },
        { stage: 6, name: "Doing", ages: "35-42", focus: "Live out practices; apply to life's journey" },
        { stage: 7, name: "Elder", ages: "42+", focus: "Teach, council, fast for guidance; mentor next cycle" },
      ],
    },
  },
  {
    uri: "medicine-wheel://wilson/framework",
    name: "Shawn Wilson's Indigenous Research Paradigm",
    description: "Research Is Ceremony (2008), with page references to the 2008 print edition",
    mimeType: "application/json",
    content: {
      citation: "Wilson, Shawn (2008). Research Is Ceremony: Indigenous Research Methods. Fernwood Publishing.",
      pages_note: "Page numbers are the 2008 print edition. Quotes are kept short; read the book for the full text. Lines credited to Peter, Cora, Lewis, Stan or Jane in pp. 99-125 come from a conversation Wilson composed from several held at different times, keeping each person's content and altering some words so they flow (p. 98).",
      core_principle: "Research is a ceremony for improving your relationship with an idea (Stan Wilson, quoted p. 110). 'Research isn't just like a ceremony, it is a ceremony' (p. 124). In the book the sentence is first Lewis Cardinal's: 'research is a ceremony' (p. 89).",
      paradigm: "Ontology, epistemology, methodology and axiology, drawn as a circle: inseparable, each blending into the next, the whole greater than the sum of its parts (p. 70; again p. 108). In one paragraph: the ontology and epistemology are a process of relationships that form a mutual reality; the axiology and methodology maintain accountability to these relationships (pp. 70-71).",
      medicine_wheel_note: "Wilson warns that a dogmatic reading of the medicine wheel, in which only one understanding of what each quadrant stands for is 'right', undermines those who use the circle as a theoretical paradigm. All parts of the circle are equal; no part can claim superiority over the rest (p. 70).",
      ontology: {
        definition: "Nature of reality",
        indigenous_view: "Relationships do not merely shape reality, they are reality (foreword, p. 7). Reality is 'not an object but a process of relationships' (p. 73); each thing is a knot where relationships come together (p. 76). 'Knowledge itself is held in the relationships and connections formed with the environment that surrounds us' (p. 87).",
        relations: "The chapter 'Relationality' is organized by four relations: with people (p. 84), with the environment/land (p. 86), with the cosmos (p. 89), with ideas (p. 91). Ancestors and future generations: Stan Wilson (p. 80); 'our ancestors ARE part of us' (p. 96). The space between people, and between people and environment, is sacred; ceremony brings them into the same space (p. 87).",
      },
      epistemology: {
        definition: "How we know what we know",
        indigenous_view: "Knowledge is relational, shared with all of creation, and cannot be owned (Wilson 2001, quoted p. 74 and pp. 56-57; p. 127). Indigenous ontology is the equivalent of Indigenous epistemology (p. 73).",
        ways_of_knowing: "Through the senses and beyond them, including putting form to a bundle of relationships previously invisible (p. 111). Empirical knowledge is crucial but not the only way of knowing (p. 58).",
      },
      axiology: {
        definition: "Ethics and values",
        indigenous_view: "Built upon relational accountability: value judgements lose their meaning; what matters is fulfilling a role and obligations in the research relationship (p. 77). You are answerable to all your relations (Wilson 2001, quoted p. 57). Respect, reciprocity and responsibility are key features of any healthy relationship and must be included in an Indigenous methodology (p. 77; p. 99).",
        three_rs_note: "Cora Weber-Pillwax calls respect, reciprocity and responsibility 'the 3 R's of Indigenous research and learning' (Wilson, p. 77). A variant of hers, quoted by Evelyn Steinhauer, has Relationality as the third R (p. 58).",
        researcher_questions: [
          "How do my methods help to build respectful relationships between the topic and myself as researcher?",
          "How do my methods help to build respectful relationships between myself and the other participants?",
          "How can we together form a stronger relationship with the idea we share?",
          "What is my role as researcher in this relationship, and what are my responsibilities?",
          "Am I fulfilling my role and obligations to the other participants, to the topic and to all my relations?",
          "What am I giving back to the relationship? Is the sharing, growth and learning reciprocal?",
        ],
        researcher_questions_source: "Wilson 2008, p. 77, condensed. Questions asked of people; no score answers them.",
      },
      methodology: {
        definition: "How the research is done",
        steps: [
          "Topic: how we choose what to study (p. 108)",
          "Methods: how we gather information (p. 110)",
          "Analysis: how we interpret information (p. 116)",
          "Presentation: how we transfer knowledge (p. 122)",
        ],
        notes: "The methodology is simply the building of more relations (p. 79). Talking circles, participatory action research, storytelling and personal narrative fit the paradigm (p. 115). The method refuses a single formula (Hermes, quoted p. 53). Choosing where to build these connections, the topic, is a responsibility (p. 79).",
      },
      key_concepts: {
        relational_accountability: "Being answerable to all your relations when doing research (Wilson 2001, quoted p. 57).",
        research_as_ceremony: "A ceremony for improving your relationship with an idea (p. 110).",
        review_not_critique: "A review that builds on the work of others, rather than judging it, can form the context for relational accountability (pp. 43-44).",
        giving_back: "Credibility through continuous feedback with all participants (p. 121); after the writing, going back to the community (Cora, p. 125).",
        presentation: "The presentation or knowledge transfer is about continuing healthy relationships (p. 125).",
        relational_accountability_in_action: "The methodology needs to be based in a community context (be relational) and has to demonstrate respect, reciprocity and responsibility (be accountable as it is put into action) (p. 99).",
        storyteller_role: "The teller's role 'is not to draw conclusions for another or to make an argument' but to share information and make connections; restating or summarizing judges some ideas as more important than others (p. 133). 'For the storyteller to explain too much is not honouring you as the listener' (p. 135).",
        not_a_manual: "The book 'is not intended to impose conclusions on other people or to be a manual of techniques for their research'; 'models do not work outside of specific contexts'; it is one version of a paradigm, a foundation and not a ceiling (p. 136). Communities develop their own guidelines and protocols (p. 136).",
        transformation: "'If research doesn't change you as a person, then you aren't doing it right', as 'one friend stated' at the 2002 Indigenous Scholars Conference (p. 83). Wilson reiterates it as a great lesson whose sharer he cannot find; the co-researchers all use it as a slogan (p. 135).",
        egalitarianism: "'Hierarchy in belief systems, social structure and thought are totally foreign to this way of viewing the world'; egalitarianism and inclusiveness are 'the epistemologically inevitable' (p. 92). In talking story, 'though you may disagree, you are not disagreeable', and a third person finds 'some mediating point that meets both views' (Peter, p. 93).",
        story_levels: "Cree Elder Jerry Saddleback, through Wilson: sacred stories, told only by 'those trained, tested and given permission', which 'must never vary'; legends, shaped by each teller with the intent kept; and personal experience, used by Elders to counsel and teach (pp. 97-98). Boundary for this suite: no tool or agent tells, generates, varies or remixes a sacred story.",
        composite_conversation: "Wilson discloses that his conversation chapter is a composite: 'It does hold true to the content of what each person said, but I have altered some of their words in order to get them to flow together'; his own words link the speakers, at the risk that 'it ends up sounding like I just took over the conversation' (p. 98).",
        credibility: "Instead of triangulation, 'encircle'; 'rather than it being valid or reliable… it's authentic or credible… it is relational' (Peter, p. 101). The test: 'Is it building relationships rather than breaking them down?' (p. 101). 'We don't need externally imposed measures or tests of whether or not something is true, we have our own ways… or questions to ask' (p. 102).",
        process_is_product: "Educate through a hierarchical process and you teach the hierarchical process: 'Therefore the process is the product' (Lewis Cardinal, p. 103). What a tool does teaches, whatever its docs say.",
        accountable_to: "'We are accountable to ourselves, the community, our environment or cosmos as a whole, and also to the idea or topics that we are researching'; researchers are 'mediators in a growing relationship between the community and whatever it is that is being researched' (p. 106).",
        natural_and_sacred_law: "Stan Wilson: in Cree, 'otcinawin' (breaking of natural law) and 'pastahowin' (breaking of a sacred law) invoke natural justice, 'even to seven generations'; 'humans, who are capable of knowing the difference, are accountable for all their actions to all their relations' (p. 107). Described, not encoded: this suite turns none of it into penalties or scores.",
        recording_reciprocity: "'I don't want there to be any feeling of me just recording your thoughts without sharing my own' (p. 100). Permission to record comes after the meal and the informal talk; then one question, and listening (Cora, p. 106).",
        restoring_relationship: "When a mistranslation broke the relationships in her grandfather's words, re-translating the text 'may have helped to correct the misinformation, but it would not have restored the relationship'; Cora's method was to go home and re-analyze it with her mother (Wilson on Weber-Pillwax, p. 78).",
        deeds_not_paper: "'You are recognized by your deeds within the Indigenous world. Not by what you say on paper: what you have done' (Lewis Cardinal, p. 91).",
        context_and_definition: "Terry Tafoya's Principle of Uncertainty, as Wilson uses it: an idea's context and its definition cannot be known at the same time; holding both is the essence of relationality (p. 99). A summary is a definition: keep its source beside it.",
        whole_as_analysis: "A conversation is a cumulative analysis and 'cannot be easily taken apart'; verbatim transcripts look jumpy because non-verbal communication is lost, and Wilson keeps the rough transitions (p. 99).",
      },
      removed: "Earlier versions listed 'wetiko disease', 'spiritual crash', 'natural law', a five-phase methodology (Prepare, Invoke, Witness, Integrate, Document) and 'once in relationship, you are responsible for its wellbeing' as key concepts of Wilson's paradigm; they were removed (jgwill/medicine-wheel#154). None is a concept of the book's paradigm. 'Natural law' appears once, as Stan's gloss of the Cree otcinawin, 'breaking of natural law' (p. 107). Wetiko and spiritual crash may come from a 2020 lecture by Wilson (model summaries; unverified against the recording); wetiko as a disease of exploitation is Jack D. Forbes's framing.",
    },
  },
  {
    uri: "medicine-wheel://two-eyed-seeing/framework",
    name: "Two-Eyed Seeing (Etuaptmumk)",
    description: "Mi'kmaw framework for integrating Indigenous and Western knowledge",
    mimeType: "application/json",
    content: {
      citation: "Bartlett, Marshall, Marshall (2007+); Wright et al. (2019) integrative review",
      definition: "Using the strengths of both Indigenous and Western ways of knowing together",
      principles: {
        equitable: "All perspectives valued; no hierarchy",
        weaving: "Back-and-forth between best of both worldviews",
        decolonizing: "Rejects Western dominance; honors Indigenous epistemology",
        co_learning: "Both perspectives teach each other; similarities & differences appreciated",
        to_betterment: "Leave world better; benefit community, not just researcher",
      },
      implementation: {
        ontology: "Relational Indigenous (interconnected) + Western (parts & wholes) → integrated whole",
        epistemology: "Holistic ceremony/story + hypothesis testing/rigor → blended rigor",
        axiology: "Relational accountability + academic standards → ethical tension resolved via Elder guidance",
        methods: "Community advisory board, Elders as co-investigators, ceremony woven through, storytelling + data",
      },
      examples: {
        health: "Sweat lodge ceremony + Western trauma therapy (e.g., Seeking Safety model); Elders + clinicians as equals",
        education: "Land-based curriculum + scientific rigor; storytelling pedagogy; students co-create knowledge",
        environment: "Bayesian models blend traditional ecological knowledge (Elders) + scientific indicators; better decisions",
      },
    },
  },
  {
    uri: "medicine-wheel://ocap/principles",
    name: "OCAP® Data Sovereignty Principles",
    description: "Ownership, Control, Access, Possession framework for First Nations data",
    mimeType: "application/json",
    content: {
      citation: "First Nations Information Governance Centre (FNIGC), established 1998",
      principles: {
        ownership: {
          definition: "Data belongs to First Nation collectively (like individual owns personal info)",
          implementation: "Community retains IP; all publications co-authored with community",
        },
        control: {
          definition: "Community controls collection, use, sharing, analysis, management",
          implementation: "Community Advisory Board has veto; researcher seeks approval at each phase",
        },
        access: {
          definition: "First Nations access own data regardless of where held; community determines access protocols",
          implementation: "Community determines who sees data; guided by cultural values",
        },
        possession: {
          definition: "Physical/digital custody with community (makes ownership enforceable)",
          implementation: "Data stored on-premise (GC Canada); not extracted; community IT oversight",
        },
      },
      integration: {
        fair: "Findable, Accessible, Interoperable, Reusable (technical layer)",
        care: "Collective benefit, Authority to control, Responsibility, Ethics (Indigenous layer)",
        together: "Respect Indigenous sovereignty while enabling scientific rigor",
      },
      tcps2_chapter9: {
        description: "Canadian Tri-Council Policy Statement requirements",
        requirements: [
          "Community engagement plan",
          "Dual REB (Institutional + Community)",
          "Community REB may override institutional REB on cultural grounds",
          "OCAP® principles must be integrated",
        ],
      },
    },
  },
  {
    uri: "medicine-wheel://methodologies/indigenous",
    name: "Indigenous Research Methodologies",
    description: "Kapati, Storywork, and Conversational methods",
    mimeType: "application/json",
    content: {
      kapati: {
        origin: "Aboriginal Australia/New Zealand (Ober)",
        description: "'Cup of tea time' - familiar, safe social space for knowledge-sharing via family interaction",
        approach: "Be true to self; draw on own epistemologies; bring whole self",
        epistemology: "Stories shared, debated, negotiated (not extracted)",
      },
      storywork: {
        origin: "Jean Archibald - Decolonizing",
        description: "Tell/retell stories from Indigenous perspectives (vs. colonial retellings)",
        principles: ["Respect", "Responsibility", "Reverence", "Reciprocity", "Holism", "Interrelatedness", "Synergy"],
        purpose: "Reclaim meaning-making from knowledge institutions; fierce Indigenous voice",
        outcome: "Transformative action for social justice; validate Indigenous knowledge systems",
      },
      conversational: {
        origin: "Kovach - Nehiyaw",
        characteristics: "Tribal epistemology, relational, purposeful (decolonizing), protocol-bound, informal, collaborative, reflexive",
        process: "Participants share stories in safe locations; ongoing conversation avoids narrative fragmentation",
        integration: "Journaling, dream attention, self-reflection throughout research",
      },
      common_threads: {
        relationality: "Everything interconnected; researchers answer to all relations",
        reciprocity: "Researcher gives back; mutual benefit (not extraction)",
        storytelling: "Primary method; oral tradition honored; stories are alive & transformative",
      },
    },
  },
];
