import type { Resource } from "../types.js";

export const resources: Resource[] = [
  {
    uri: "medicine-wheel://directions/all",
    name: "Medicine Wheel - Four Directions",
    description: "Complete teachings for all four sacred directions from Ojibwe/Anishinaabe tradition",
    mimeType: "application/json",
    content: {
      east: {
        ojibwe: "Waabinong",
        color: "Yellow",
        season: "Spring",
        life_stage: "Birth to 7 years",
        stage_name: "Good Life",
        medicine: ["Tobacco"],
        element: "Spirit entering physical world",
        teachings: [
          "New beginnings and vision",
          "Creator gifts: choice of parents, spiritual journey, growth",
          "Daily thanksgiving and gratitude for all relations",
          "First day-fast at age 7",
        ],
        practices: [
          "Place tobacco outside daily",
          "Acknowledge all relations",
          "Opening ceremonies",
          "Vision inquiry",
        ],
        research_application: "Vision inquiry, new ideas, opening ceremonies, honor knowledge's aliveness",
      },
      south: {
        ojibwe: "Zhaawanong",
        color: "Red",
        season: "Summer",
        life_stage: "7 to 14 years",
        stage_name: "Fast Life / Wandering into Youth",
        medicine: ["Cedar (Grandmother)"],
        element: "Life awake and dancing",
        teachings: [
          "Growth and embodiment",
          "Spirit nurturance critical",
          "Elders invite, don't command",
          "Mentorship heals",
          "Intuition never deceives",
        ],
        practices: [
          "Sweat lodges",
          "Dancing and celebration",
          "Berry harvesting",
          "Listen to spirit's warnings",
        ],
        research_application: "Physical embodiment, land engagement, growth practices, youth participation, hands-on learning",
      },
      west: {
        ojibwe: "Epangishmok",
        color: "Black",
        season: "Fall",
        life_stage: "35 to 49 years",
        stage_name: "Truth & Planning",
        medicine: ["Sage", "Strawberry"],
        element: "Ripening harvest, adult responsibility, transformation",
        teachings: [
          "Death not ending but continuous transformation",
          "Accept change and loss",
          "Heart (not head) leads to peace",
          "Forgiveness through strawberry teaching",
        ],
        practices: [
          "Talking circles",
          "Dream work",
          "Storytelling",
          "Smudging with sage",
          "Forgiveness ceremonies",
        ],
        research_application: "Reflection, emotional processing, relational healing, unpacking trauma, forgiveness frameworks",
        strawberry_teaching: "Brother kills brother; mourns years; strawberry grows on grave; eating berry = freedom (release of blame)",
      },
      north: {
        ojibwe: "Kiiwedinong",
        color: "White",
        season: "Winter",
        life_stage: "49+ years",
        stage_name: "Doing & Elder",
        medicine: ["Cedar", "Stories"],
        element: "Rest, reflection, wisdom, remembrance",
        teachings: [
          "Elders teach via ceremony and story",
          "Feed ancestors (maintain relational continuity)",
          "Wisdom = integration of all stages",
          "Winter storytelling circles",
        ],
        practices: [
          "Spirit feeding ceremonies",
          "Winter storytelling",
          "Fasting for direction every 7 years",
          "Elder councils",
          "Feast gatherings",
        ],
        research_application: "Wisdom synthesis, ancestral consultation, long-term reflection, community teaching, closing ceremonies",
        spirit_feeding: "Bakademe – zhamzhenung (We are hungry; feed us) - call to feed ancestors",
      },
      seven_stages: [
        { stage: 1, name: "Good Life", ages: "0-7", focus: "Unconditional love, identity grounding, first fast" },
        { stage: 2, name: "Fast Life", ages: "7-14", focus: "Vision quest prep, gendered mentorship, circle induction" },
        { stage: 3, name: "Wandering", ages: "14-21", focus: "Find teachers, explore ('I wonder...'), discover self" },
        { stage: 4, name: "Truth", ages: "21-28", focus: "Mirror self, name gifts, speak truth" },
        { stage: 5, name: "Planning", ages: "28-35", focus: "Integrate learning into action strategy" },
        { stage: 6, name: "Doing", ages: "35-42", focus: "Live out practices; apply to life's journey" },
        { stage: 7, name: "Elder", ages: "42+", focus: "Teach, council, fast for guidance; mentor next cycle" },
      ],
    },
  },
  {
    uri: "medicine-wheel://wilson/framework",
    name: "Shawn Wilson's Indigenous Research Paradigm",
    description: "Ontology, epistemology, axiology framework from Research is Ceremony",
    mimeType: "application/json",
    content: {
      citation: "Wilson, Shawn (2008). Research is Ceremony: Indigenous Research Methods. Fernwood Publishing.",
      core_principle: "Research as ceremony - sacred act of building and maintaining relationships",
      ontology: {
        definition: "Nature of reality",
        indigenous_view: "Reality is relational; everything interconnected; identity = roles in relationships",
        teaching: "Once in relationship, you are responsible for that relationship's wellbeing",
        contrast_western: "Western: Reality as separate objects/individuals; Indigenous: Reality as web of relationships",
      },
      epistemology: {
        definition: "How we know what we know",
        indigenous_view: "Knowledge co-created via relations, stories, land observation, ceremony; not extracted",
        teaching: "Knowledge has spirit; treat respectfully, not as property",
        methods: "Storytelling, ceremony, land-based learning, Elder teachings, dreams",
      },
      axiology: {
        definition: "Ethics and values",
        indigenous_view: "Relational accountability; researcher answers to all relations; reciprocity mandatory",
        teaching: "Researcher must live congruently with topic; embody values researched",
        accountability: "To all relations: human, land, spirit, ancestors, future generations",
      },
      methodology: {
        definition: "Strategies for sacred engagement",
        phases: ["Prepare (ceremony)", "Invoke (spirits/ancestors)", "Witness (deep listening)", "Integrate (meaning-making)", "Document (honor stories)"],
      },
      key_concepts: {
        relational_accountability: "Once in relationship, responsible for wellbeing of that relationship",
        wetiko_disease: "Colonial illness of greed and disconnection; symptoms: individualism, extraction, commodification; cure: laughter, willpower, relational repair",
        spiritual_crash: "When spirit and action misaligned; resolved through ceremony and living congruently",
        natural_law: "Living in right relationship with all relations",
      },
    },
  },
  {
    uri: "medicine-wheel://two-eyed-seeing/framework",
    name: "Two-Eyed Seeing (Etuaptmumk)",
    description: "Mi'kmaw framework for integrating Indigenous and Western knowledge",
    mimeType: "application/json",
    content: {
      citation: "Bartlett, Marshall, Marshall (2007+); Wright et al. (2019) integrative review",
      definition: "Using the strengths of both Indigenous and Western ways of knowing together",
      principles: {
        equitable: "All perspectives valued; no hierarchy",
        weaving: "Back-and-forth between best of both worldviews",
        decolonizing: "Rejects Western dominance; honors Indigenous epistemology",
        co_learning: "Both perspectives teach each other; similarities & differences appreciated",
        to_betterment: "Leave world better; benefit community, not just researcher",
      },
      implementation: {
        ontology: "Relational Indigenous (interconnected) + Western (parts & wholes) → integrated whole",
        epistemology: "Holistic ceremony/story + hypothesis testing/rigor → blended rigor",
        axiology: "Relational accountability + academic standards → ethical tension resolved via Elder guidance",
        methods: "Community advisory board, Elders as co-investigators, ceremony woven through, storytelling + data",
      },
      examples: {
        health: "Sweat lodge ceremony + Western trauma therapy (e.g., Seeking Safety model); Elders + clinicians as equals",
        education: "Land-based curriculum + scientific rigor; storytelling pedagogy; students co-create knowledge",
        environment: "Bayesian models blend traditional ecological knowledge (Elders) + scientific indicators; better decisions",
      },
    },
  },
  {
    uri: "medicine-wheel://ocap/principles",
    name: "OCAP® Data Sovereignty Principles",
    description: "Ownership, Control, Access, Possession framework for First Nations data",
    mimeType: "application/json",
    content: {
      citation: "First Nations Information Governance Centre (FNIGC), established 1998",
      principles: {
        ownership: {
          definition: "Data belongs to First Nation collectively (like individual owns personal info)",
          implementation: "Community retains IP; all publications co-authored with community",
        },
        control: {
          definition: "Community controls collection, use, sharing, analysis, management",
          implementation: "Community Advisory Board has veto; researcher seeks approval at each phase",
        },
        access: {
          definition: "First Nations access own data regardless of where held; community determines access protocols",
          implementation: "Community determines who sees data; guided by cultural values",
        },
        possession: {
          definition: "Physical/digital custody with community (makes ownership enforceable)",
          implementation: "Data stored on-premise (GC Canada); not extracted; community IT oversight",
        },
      },
      integration: {
        fair: "Findable, Accessible, Interoperable, Reusable (technical layer)",
        care: "Collective benefit, Authority to control, Responsibility, Ethics (Indigenous layer)",
        together: "Respect Indigenous sovereignty while enabling scientific rigor",
      },
      tcps2_chapter9: {
        description: "Canadian Tri-Council Policy Statement requirements",
        requirements: [
          "Community engagement plan",
          "Dual REB (Institutional + Community)",
          "Community REB may override institutional REB on cultural grounds",
          "OCAP® principles must be integrated",
        ],
      },
    },
  },
  {
    uri: "medicine-wheel://methodologies/indigenous",
    name: "Indigenous Research Methodologies",
    description: "Kapati, Storywork, and Conversational methods",
    mimeType: "application/json",
    content: {
      kapati: {
        origin: "Aboriginal Australia/New Zealand (Ober)",
        description: "'Cup of tea time' - familiar, safe social space for knowledge-sharing via family interaction",
        approach: "Be true to self; draw on own epistemologies; bring whole self",
        epistemology: "Stories shared, debated, negotiated (not extracted)",
      },
      storywork: {
        origin: "Jean Archibald - Decolonizing",
        description: "Tell/retell stories from Indigenous perspectives (vs. colonial retellings)",
        principles: ["Respect", "Responsibility", "Reverence", "Reciprocity", "Holism", "Interrelatedness", "Synergy"],
        purpose: "Reclaim meaning-making from knowledge institutions; fierce Indigenous voice",
        outcome: "Transformative action for social justice; validate Indigenous knowledge systems",
      },
      conversational: {
        origin: "Kovach - Nehiyaw",
        characteristics: "Tribal epistemology, relational, purposeful (decolonizing), protocol-bound, informal, collaborative, reflexive",
        process: "Participants share stories in safe locations; ongoing conversation avoids narrative fragmentation",
        integration: "Journaling, dream attention, self-reflection throughout research",
      },
      common_threads: {
        relationality: "Everything interconnected; researchers answer to all relations",
        reciprocity: "Researcher gives back; mutual benefit (not extraction)",
        storytelling: "Primary method; oral tradition honored; stories are alive & transformative",
      },
    },
  },
];
